#!/bin/sh

#
# lazy umount hook
#

if [ "$1" == "-l" ]
then
    shift
    /bin/umount "$@" \
    && echo umount success "$@" $(date) >> /tmp/usbdebug-umount \
    && exit 0 \
    || echo umount failure "$@" $(date) >> /tmp/usbdebug-umount
    # undo shift
    set -- -l "$@"
fi

exec /bin/umount "$@"
