#!/bin/busybox sh

echo '::respawn:/sbin/my-inetd -f /etc/my-inetd.conf' >> /etc/inittab

rm /sbin/hwclock && ln -s ../bin/busybox /sbin/hwclock && sync

rm /etc/udev/rules.d/telnetftp.rules
rm /sbin/my-telnetftp
